// File generated by FlutterFire CLI & configured with cross-platform fallback
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_JkZEIh4gE5Yd8LbOSE9DclmsRBuQ3ko',
    appId: '1:257897538766:android:1f86f86ebdd170a73d9c9f',
    messagingSenderId: '257897538766',
    projectId: 'flutter-mega-assignment',
    storageBucket: 'flutter-mega-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_JkZEIh4gE5Yd8LbOSE9DclmsRBuQ3ko',
    appId: '1:257897538766:ios:1f86f86ebdd170a73d9c9f',
    messagingSenderId: '257897538766',
    projectId: 'flutter-mega-assignment',
    storageBucket: 'flutter-mega-assignment.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_JkZEIh4gE5Yd8LbOSE9DclmsRBuQ3ko',
    appId: '1:257897538766:ios:1f86f86ebdd170a73d9c9f',
    messagingSenderId: '257897538766',
    projectId: 'flutter-mega-assignment',
    storageBucket: 'flutter-mega-assignment.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_JkZEIh4gE5Yd8LbOSE9DclmsRBuQ3ko',
    appId: '1:257897538766:web:1f86f86ebdd170a73d9c9f',
    messagingSenderId: '257897538766',
    projectId: 'flutter-mega-assignment',
    storageBucket: 'flutter-mega-assignment.firebasestorage.app',
  );
}
