import 'package:flutter/material.dart';
import '../../models/product_model.dart';

class CategoryItem {
  final String id;
  final String name;
  final IconData icon;

  const CategoryItem({
    required this.id,
    required this.name,
    required this.icon,
  });
}

class PromoBanner {
  final String title;
  final String subtitle;
  final String discount;
  final String imageUrl;
  final Color backgroundColor;

  const PromoBanner({
    required this.title,
    required this.subtitle,
    required this.discount,
    required this.imageUrl,
    required this.backgroundColor,
  });
}

class AppConstants {
  // Currency and Pricing (BDT - ৳)
  static const String currencySymbol = '৳';

  static String formatCurrency(num amount) {
    final isInt = amount.truncateToDouble() == amount;
    final formatted = isInt ? amount.toInt().toString() : amount.toStringAsFixed(2);
    return '$currencySymbol$formatted';
  }

  // Delivery Charges by Zone
  static const double deliveryFeeDhaka = 60.0;
  static const double deliveryFeeOutsideDhaka = 120.0;
  static const double taxRate = 0.05; // 5% VAT / Tax

  // Price Slider Range
  static const double minPriceSlider = 0.0;
  static const double maxPriceSlider = 100000.0;

  // Bangladeshi Phone Number Validation (01XXXXXXXXX, 11 digits, optional +880/880)
  static final RegExp bdPhoneRegex = RegExp(r'^(?:\+880|880|0)?(1[3-9]\d{8})$');

  static bool isValidPhone(String? phone) {
    if (phone == null || phone.trim().isEmpty) return false;
    final clean = phone.trim().replaceAll(' ', '').replaceAll('-', '');
    return bdPhoneRegex.hasMatch(clean);
  }

  static String normalizePhone(String phone) {
    final clean = phone.trim().replaceAll(' ', '').replaceAll('-', '');
    final match = bdPhoneRegex.firstMatch(clean);
    if (match != null && match.groupCount >= 1) {
      return '0${match.group(1)}';
    }
    return clean;
  }

  static const List<CategoryItem> categories = [
    CategoryItem(id: 'All', name: 'All', icon: Icons.grid_view_rounded),
    CategoryItem(id: 'Electronics', name: 'Electronics', icon: Icons.devices_rounded),
    CategoryItem(id: 'Footwear', name: 'Footwear', icon: Icons.roller_skating_outlined),
    CategoryItem(id: 'Audio', name: 'Audio', icon: Icons.headphones_rounded),
    CategoryItem(id: 'Watches', name: 'Watches', icon: Icons.watch_outlined),
    CategoryItem(id: 'Fashion', name: 'Fashion', icon: Icons.checkroom_rounded),
  ];

  static const List<PromoBanner> promoBanners = [
    PromoBanner(
      title: 'Mega Summer Sale',
      subtitle: 'Premium Tech & Gear',
      discount: 'UP TO 40% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      backgroundColor: Color(0xFF312E81),
    ),
    PromoBanner(
      title: 'Fresh Sneakers Drop',
      subtitle: 'Style Meets Comfort',
      discount: 'NEW ARRIVALS',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      backgroundColor: Color(0xFF831843),
    ),
    PromoBanner(
      title: 'Smart Wearables',
      subtitle: 'Track Your Health Today',
      discount: 'EXTRA 20% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      backgroundColor: Color(0xFF064E3B),
    ),
  ];

  static List<ProductModel> get initialProducts => [
    // ── AUDIO (10 products) ──────────────────────────────────────────────
    ProductModel(
      id: 'prod_1',
      name: 'Sony WH-1000XM5 Wireless Headphones',
      brand: 'Sony',
      category: 'Audio',
      price: 34900.0,
      originalPrice: 39900.0,
      rating: 4.8,
      reviewCount: 342,
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      description: 'Industry-leading noise cancellation with two processors and eight microphones. Exceptional sound quality with newly developed 30mm driver unit and crystal-clear hands-free calling.',
      colors: ['Black', 'Silver', 'Midnight Blue'],
      sizes: ['Standard'],
      isFeatured: true,
      inStock: true,
      stockCount: 15,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_5',
      name: 'JBL Charge 5 Portable Bluetooth Speaker',
      brand: 'JBL',
      category: 'Audio',
      price: 13900.0,
      originalPrice: 17900.0,
      rating: 4.6,
      reviewCount: 420,
      imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
      description: 'Take the party with you no matter what the weather. The JBL Charge 5 delivers bold JBL Original Pro Sound with optimized long-excursion driver and separate tweeter.',
      colors: ['Teal', 'Squad Camo', 'Black'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 30,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_11',
      name: 'Apple AirPods Pro (2nd Gen)',
      brand: 'Apple',
      category: 'Audio',
      price: 29900.0,
      originalPrice: 32900.0,
      rating: 4.9,
      reviewCount: 780,
      imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&q=80',
      description: 'Rebuilt from the ground up: the Apple‑designed H2 chip powers smarter noise cancellation, richer Adaptive Audio, and even more personalized spatial audio.',
      colors: ['White'],
      sizes: ['Standard'],
      isFeatured: true,
      inStock: true,
      stockCount: 20,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_12',
      name: 'Bose QuietComfort 45 Headphones',
      brand: 'Bose',
      category: 'Audio',
      price: 27900.0,
      originalPrice: 32500.0,
      rating: 4.7,
      reviewCount: 215,
      imageUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=800&q=80',
      description: 'World-class noise cancellation meets the comfort and simplicity of QuietComfort. Up to 24 hours battery life with 15-minute quick charge for 3 more hours.',
      colors: ['Triple Black', 'White Smoke'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 12,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_13',
      name: 'Marshall Emberton II Portable Speaker',
      brand: 'Marshall',
      category: 'Audio',
      price: 18500.0,
      originalPrice: 21000.0,
      rating: 4.6,
      reviewCount: 134,
      imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      description: 'True wireless stereo with up to 30 hours of playtime. IP67 waterproof and dustproof. Multi-directional sound inspired by classic Marshall style.',
      colors: ['Black & Brass', 'Cream'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 18,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_14',
      name: 'Samsung Galaxy Buds2 Pro',
      brand: 'Samsung',
      category: 'Audio',
      price: 17900.0,
      originalPrice: 21900.0,
      rating: 4.5,
      reviewCount: 290,
      imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
      description: 'Hi-Fi 24-bit audio, intelligent ANC, and 3-mic system with Wind Shield for premium true wireless sound. Up to 18 hours total battery with case.',
      colors: ['Graphite', 'White', 'Bora Purple'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 22,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_15',
      name: 'Harman Kardon Aura Studio 3',
      brand: 'Harman Kardon',
      category: 'Audio',
      price: 22900.0,
      originalPrice: 27000.0,
      rating: 4.4,
      reviewCount: 87,
      imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
      description: 'Glass dome and 360-degree sound field deliver an immersive audio experience. Wireless streaming via Bluetooth 5.0 and stunning LED light show.',
      colors: ['Black', 'White'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 9,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_16',
      name: 'Sennheiser HD 560S Over-Ear Headphones',
      brand: 'Sennheiser',
      category: 'Audio',
      price: 16500.0,
      originalPrice: 19500.0,
      rating: 4.7,
      reviewCount: 160,
      imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
      description: 'Open-back audiophile headphones with wide soundstage, precise imaging, and exceptionally transparent sound. Lightweight design for extended listening sessions.',
      colors: ['Black'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 7,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_17',
      name: 'Anker Soundcore P40i Earbuds',
      brand: 'Anker',
      category: 'Audio',
      price: 4500.0,
      originalPrice: 5990.0,
      rating: 4.4,
      reviewCount: 320,
      imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
      description: 'Adaptive ANC with adjustable levels, LDAC Hi-Res audio, and 50 hours total playtime. IPX5 water resistance for gym and outdoor use.',
      colors: ['Black', 'White', 'Navy'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 40,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_18',
      name: 'Bang & Olufsen Beoplay H95 Headphones',
      brand: 'Bang & Olufsen',
      category: 'Audio',
      price: 89900.0,
      originalPrice: 99900.0,
      rating: 4.8,
      reviewCount: 45,
      imageUrl: 'https://images.unsplash.com/photo-1578319439584-104c94d37305?w=800&q=80',
      description: 'Premium titanium over-ear headphones with adaptive ANC, 38-hour playtime, and luxurious lambskin cushions. Handcrafted in Denmark.',
      colors: ['Black Anthracite', 'Gold Tone'],
      sizes: ['Standard'],
      isFeatured: true,
      inStock: true,
      stockCount: 4,
      unit: 'pcs',
      isDeleted: false,
    ),

    // ── WATCHES (8 products) ─────────────────────────────────────────────
    ProductModel(
      id: 'prod_3',
      name: 'Apple Watch Ultra 2 Titanium Case',
      brand: 'Apple',
      category: 'Watches',
      price: 79900.0,
      originalPrice: 84900.0,
      rating: 4.9,
      reviewCount: 512,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      description: 'The most rugged and capable Apple Watch. Built for outdoor adventures with a lightweight 49mm titanium case, extra-long battery life, and high-precision GPS.',
      colors: ['Titanium Natural', 'Dark Titanium'],
      sizes: ['49mm'],
      isFeatured: true,
      inStock: true,
      stockCount: 8,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_6',
      name: 'Fossil Classic Leather Chronograph',
      brand: 'Fossil',
      category: 'Watches',
      price: 12900.0,
      originalPrice: 16500.0,
      rating: 4.5,
      reviewCount: 118,
      imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80',
      description: 'Timeless silhouette featuring a rich brown genuine leather strap, sunray blue dial, and Japanese quartz chronograph movement. Water-resistant up to 50 meters.',
      colors: ['Brown / Navy', 'Black / Silver'],
      sizes: ['42mm'],
      isFeatured: false,
      inStock: true,
      stockCount: 12,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_19',
      name: 'Samsung Galaxy Watch 6 Classic',
      brand: 'Samsung',
      category: 'Watches',
      price: 36900.0,
      originalPrice: 42900.0,
      rating: 4.6,
      reviewCount: 178,
      imageUrl: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&q=80',
      description: 'Classic rotating bezel, advanced health monitoring with BioActive Sensor, and up to 40-hour battery life. Wear OS with Google apps integration.',
      colors: ['Black', 'Silver', 'Cream'],
      sizes: ['43mm', '47mm'],
      isFeatured: false,
      inStock: true,
      stockCount: 10,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_20',
      name: 'Seiko Presage Sharp Edged Automatic',
      brand: 'Seiko',
      category: 'Watches',
      price: 42900.0,
      originalPrice: 49900.0,
      rating: 4.8,
      reviewCount: 64,
      imageUrl: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=80',
      description: 'Japanese automatic movement with 45-hour power reserve. Inspired by traditional Japanese craftsmanship with hand-applied indices and a stunning gradient dial.',
      colors: ['Blue Gradient', 'Green Gradient'],
      sizes: ['40.2mm'],
      isFeatured: true,
      inStock: true,
      stockCount: 6,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_21',
      name: 'Garmin Fenix 7 Pro Solar GPS Watch',
      brand: 'Garmin',
      category: 'Watches',
      price: 89900.0,
      originalPrice: 99000.0,
      rating: 4.8,
      reviewCount: 234,
      imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
      description: 'Multi-sport GPS smartwatch with solar charging, 300+ ready-to-use apps, and advanced training metrics. Built tough with Power Sapphire lens.',
      colors: ['Carbon Gray DLC', 'Silver Whitestone'],
      sizes: ['47mm', '51mm'],
      isFeatured: false,
      inStock: true,
      stockCount: 5,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_22',
      name: 'Casio G-Shock GBD-H2000 Smartwatch',
      brand: 'Casio',
      category: 'Watches',
      price: 22900.0,
      originalPrice: 27500.0,
      rating: 4.5,
      reviewCount: 95,
      imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80',
      description: 'G-SHOCK toughness meets smartwatch functionality. GPS, heart rate monitor, compass, and up to 26-day battery. 200M water resistant.',
      colors: ['Black', 'Red'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 11,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_23',
      name: 'Orient Bambino Classic Automatic',
      brand: 'Orient',
      category: 'Watches',
      price: 14500.0,
      originalPrice: 17000.0,
      rating: 4.7,
      reviewCount: 142,
      imageUrl: 'https://images.unsplash.com/photo-1600959907703-b4fa59012e48?w=800&q=80',
      description: 'Elegant dress watch powered by Orient\'s in-house automatic movement. Domed dial, stainless steel case, and genuine leather strap.',
      colors: ['White / Brown', 'Black / Black'],
      sizes: ['40.5mm'],
      isFeatured: false,
      inStock: true,
      stockCount: 16,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_24',
      name: 'Xiaomi Smart Band 8 Pro',
      brand: 'Xiaomi',
      category: 'Watches',
      price: 4990.0,
      originalPrice: 6500.0,
      rating: 4.3,
      reviewCount: 280,
      imageUrl: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80',
      description: 'AMOLED display, 150+ fitness modes, SpO2 monitoring, and up to 14 days battery. Lightweight and stylish for all-day wear.',
      colors: ['Black', 'White', 'Gold'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 35,
      unit: 'pcs',
      isDeleted: false,
    ),

    // ── ELECTRONICS (12 products) ────────────────────────────────────────
    ProductModel(
      id: 'prod_4',
      name: 'Apple MacBook Pro 14" M3 Pro',
      brand: 'Apple',
      category: 'Electronics',
      price: 199900.0,
      originalPrice: 209900.0,
      rating: 4.9,
      reviewCount: 190,
      imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
      description: 'Empowered by M3 Pro chip with up to 12-core CPU and 18-core GPU. Liquid Retina XDR display with ProMotion and battery life up to 18 hours.',
      colors: ['Space Black', 'Silver'],
      sizes: ['512GB SSD', '1TB SSD'],
      isFeatured: true,
      inStock: true,
      stockCount: 5,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_8',
      name: 'Sony PlayStation 5 DualSense Controller',
      brand: 'Sony',
      category: 'Electronics',
      price: 6990.0,
      originalPrice: 7490.0,
      rating: 4.9,
      reviewCount: 650,
      imageUrl: 'https://images.unsplash.com/photo-1606318801954-d46d46d3360a?w=800&q=80',
      description: 'Discover a deeper gaming experience with haptic feedback, adaptive triggers, and built-in microphone integrated into an iconic design.',
      colors: ['White', 'Cosmic Red', 'Midnight Black'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 25,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_25',
      name: 'Samsung Galaxy S24 Ultra 5G',
      brand: 'Samsung',
      category: 'Electronics',
      price: 149900.0,
      originalPrice: 159900.0,
      rating: 4.8,
      reviewCount: 420,
      imageUrl: 'https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=800&q=80',
      description: 'Titanium design with built-in S Pen, 200MP main camera, and Snapdragon 8 Gen 3. 100x Space Zoom and 5000mAh battery with 45W fast charging.',
      colors: ['Titanium Black', 'Titanium Gray', 'Titanium Violet'],
      sizes: ['256GB', '512GB', '1TB'],
      isFeatured: true,
      inStock: true,
      stockCount: 12,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_26',
      name: 'iPad Pro 12.9" M2 Wi-Fi',
      brand: 'Apple',
      category: 'Electronics',
      price: 124900.0,
      originalPrice: 134900.0,
      rating: 4.8,
      reviewCount: 267,
      imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
      description: 'Superfast M2 chip, Liquid Retina XDR display, and ProRes video. Apple Pencil (2nd gen) and Magic Keyboard support for professional workflows.',
      colors: ['Silver', 'Space Gray'],
      sizes: ['256GB', '512GB', '1TB', '2TB'],
      isFeatured: false,
      inStock: true,
      stockCount: 8,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_27',
      name: 'Asus ROG Zephyrus G14 Gaming Laptop',
      brand: 'Asus',
      category: 'Electronics',
      price: 154900.0,
      originalPrice: 169900.0,
      rating: 4.7,
      reviewCount: 138,
      imageUrl: 'https://images.unsplash.com/photo-1593640495253-23196b27a87f?w=800&q=80',
      description: 'AMD Ryzen 9 7940HS and RTX 4070 in a compact 14" chassis. AniMe Matrix LED lid display, 165Hz QHD screen, and MUX Switch.',
      colors: ['Eclipse Gray', 'Moonlight White'],
      sizes: ['512GB SSD', '1TB SSD'],
      isFeatured: true,
      inStock: true,
      stockCount: 6,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_28',
      name: 'Canon EOS R50 Mirrorless Camera',
      brand: 'Canon',
      category: 'Electronics',
      price: 79900.0,
      originalPrice: 89000.0,
      rating: 4.7,
      reviewCount: 95,
      imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
      description: '24.2MP APS-C CMOS sensor, Dual Pixel CMOS AF II, and 4K 30p video. Compact and lightweight body perfect for vlogging and travel photography.',
      colors: ['Black', 'White'],
      sizes: ['Body Only', 'With 18-45mm Lens'],
      isFeatured: false,
      inStock: true,
      stockCount: 7,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_29',
      name: 'Logitech MX Master 3S Mouse',
      brand: 'Logitech',
      category: 'Electronics',
      price: 9900.0,
      originalPrice: 12900.0,
      rating: 4.8,
      reviewCount: 380,
      imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
      description: '8000 DPI sensor with 0 noise clicks, MagSpeed electromagnetic scrolling, and ergonomic shape. Works on glass, connects up to 3 devices.',
      colors: ['Graphite', 'Pale Gray', 'Midnight Black'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 28,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_30',
      name: 'LG 27" 4K UHD IPS Monitor',
      brand: 'LG',
      category: 'Electronics',
      price: 42900.0,
      originalPrice: 49900.0,
      rating: 4.6,
      reviewCount: 210,
      imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
      description: '27" IPS 4K UHD (3840x2160) display with USB-C 60W power delivery, HDR10, sRGB 99% coverage, and VESA mount support.',
      colors: ['Black'],
      sizes: ['27"'],
      isFeatured: false,
      inStock: true,
      stockCount: 9,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_31',
      name: 'DJI Mini 4 Pro Drone',
      brand: 'DJI',
      category: 'Electronics',
      price: 89900.0,
      originalPrice: 99900.0,
      rating: 4.8,
      reviewCount: 156,
      imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80',
      description: '4K/60fps video, omnidirectional obstacle sensing, and 34-minute flight time. Under 249g — no registration required in most regions.',
      colors: ['Gray'],
      sizes: ['Standard', 'Fly More Combo'],
      isFeatured: true,
      inStock: true,
      stockCount: 10,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_32',
      name: 'Anker 100W GaN Charger (4-Port)',
      brand: 'Anker',
      category: 'Electronics',
      price: 3990.0,
      originalPrice: 5500.0,
      rating: 4.6,
      reviewCount: 490,
      imageUrl: 'https://images.unsplash.com/photo-1583394293288-5f4b74b28af7?w=800&q=80',
      description: 'Charge 4 devices simultaneously with GaN II technology. Two USB-C ports up to 65W each, two USB-A ports. Universal voltage compatibility.',
      colors: ['Black', 'White'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 50,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_33',
      name: 'Samsung 49" Odyssey Neo G9 Monitor',
      brand: 'Samsung',
      category: 'Electronics',
      price: 249900.0,
      originalPrice: 279900.0,
      rating: 4.6,
      reviewCount: 78,
      imageUrl: 'https://images.unsplash.com/photo-1593640408182-31c228a77b7e?w=800&q=80',
      description: 'Super ultra-wide 32:9 curved display with Quantum Mini LED, 240Hz refresh rate, 1ms response time, and G-Sync Ultimate support.',
      colors: ['Black'],
      sizes: ['49"'],
      isFeatured: false,
      inStock: true,
      stockCount: 3,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_34',
      name: 'Raspberry Pi 5 (8GB)',
      brand: 'Raspberry Pi',
      category: 'Electronics',
      price: 8900.0,
      originalPrice: 9900.0,
      rating: 4.7,
      reviewCount: 112,
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
      description: 'Quad-core 64-bit Arm Cortex-A76 at 2.4GHz, dual 4Kp60 HDMI output, PCIe 2.0 x1, and real-time clock. Perfect for DIY projects.',
      colors: ['Green'],
      sizes: ['4GB', '8GB'],
      isFeatured: false,
      inStock: true,
      stockCount: 22,
      unit: 'pcs',
      isDeleted: false,
    ),

    // ── FOOTWEAR (10 products) ───────────────────────────────────────────
    ProductModel(
      id: 'prod_2',
      name: 'Nike Air Max 270 React Sneakers',
      brand: 'Nike',
      category: 'Footwear',
      price: 15900.0,
      originalPrice: 18000.0,
      rating: 4.7,
      reviewCount: 289,
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      description: 'The Nike Air Max 270 React blends artful materials with responsive Nike React foam cushioning and a large Max Air unit for smooth, ultra-comfortable stride.',
      colors: ['Red', 'White', 'Black'],
      sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
      isFeatured: true,
      inStock: true,
      stockCount: 22,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_9',
      name: 'Adidas Originals Superstar Shoes',
      brand: 'Adidas',
      category: 'Footwear',
      price: 9500.0,
      originalPrice: 11000.0,
      rating: 4.6,
      reviewCount: 310,
      imageUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
      description: 'The legendary silhouette with signature shell-toe design. Crafted from smooth leather with serrated 3-Stripes and authentic rubber cupsole.',
      colors: ['White / Black', 'All White', 'Black / White'],
      sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
      isFeatured: false,
      inStock: true,
      stockCount: 14,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_35',
      name: 'Vans Old Skool Classic Sk8',
      brand: 'Vans',
      category: 'Footwear',
      price: 8990.0,
      originalPrice: 10500.0,
      rating: 4.6,
      reviewCount: 445,
      imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
      description: 'The iconic Old Skool is a classic skate shoe with the signature side stripe. Durable canvas and suede upper with waffle outsole for superior grip.',
      colors: ['Black / White', 'Navy / White', 'True White'],
      sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
      isFeatured: false,
      inStock: true,
      stockCount: 30,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_36',
      name: 'New Balance 574 Core Sneakers',
      brand: 'New Balance',
      category: 'Footwear',
      price: 11500.0,
      originalPrice: 13500.0,
      rating: 4.7,
      reviewCount: 199,
      imageUrl: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=800&q=80',
      description: 'Timeless 574 silhouette with ENCAP midsole technology for lasting support and comfort. Suede and mesh upper for breathability.',
      colors: ['Gray / White', 'Navy / Silver', 'Red / Gray'],
      sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 12'],
      isFeatured: false,
      inStock: true,
      stockCount: 18,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_37',
      name: 'Puma RS-X Bold Chunky Sneakers',
      brand: 'Puma',
      category: 'Footwear',
      price: 10500.0,
      originalPrice: 13000.0,
      rating: 4.4,
      reviewCount: 133,
      imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
      description: 'Bold chunky design fusing retro running aesthetics with modern materials. RS cushioning technology in the heel for superior comfort.',
      colors: ['White / Multi', 'Black / Gold'],
      sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
      isFeatured: false,
      inStock: true,
      stockCount: 15,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_38',
      name: 'Converse Chuck Taylor All Star Hi',
      brand: 'Converse',
      category: 'Footwear',
      price: 7500.0,
      originalPrice: 9000.0,
      rating: 4.5,
      reviewCount: 610,
      imageUrl: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80',
      description: 'The world\'s most iconic high-top sneaker. Canvas upper, rubber toe cap, and classic ankle patch — unchanged since 1917 for a reason.',
      colors: ['Optical White', 'Monochrome Black', 'Navy'],
      sizes: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
      isFeatured: false,
      inStock: true,
      stockCount: 38,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_39',
      name: 'Timberland 6-Inch Premium Boot',
      brand: 'Timberland',
      category: 'Footwear',
      price: 19900.0,
      originalPrice: 23000.0,
      rating: 4.7,
      reviewCount: 275,
      imageUrl: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80',
      description: 'Iconic nubuck leather construction with seam-sealed waterproof protection and lug outsole. Anti-fatigue technology for all-day comfort.',
      colors: ['Wheat Nubuck', 'Black', 'Brown Smooth'],
      sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
      isFeatured: true,
      inStock: true,
      stockCount: 14,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_40',
      name: 'Birkenstock Arizona Birko-Flor',
      brand: 'Birkenstock',
      category: 'Footwear',
      price: 9900.0,
      originalPrice: 12500.0,
      rating: 4.6,
      reviewCount: 188,
      imageUrl: 'https://images.unsplash.com/photo-1544441452-d8a9f9a1f39e?w=800&q=80',
      description: 'The iconic two-strap sandal with anatomically shaped cork-latex footbed, contoured arch support, and vegan Birko-Flor upper.',
      colors: ['Stone', 'Black', 'Tobacco Brown'],
      sizes: ['EU 36', 'EU 37', 'EU 38', 'EU 39', 'EU 40', 'EU 41', 'EU 42'],
      isFeatured: false,
      inStock: true,
      stockCount: 20,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_41',
      name: 'Jordan 1 Retro High OG',
      brand: 'Nike',
      category: 'Footwear',
      price: 25900.0,
      originalPrice: 29900.0,
      rating: 4.9,
      reviewCount: 340,
      imageUrl: 'https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800&q=80',
      description: 'The shoe that started it all returns in premium leather construction. Full-length Air-Sole unit and durable rubber outsole with pivot circle.',
      colors: ['University Blue', 'Chicago Red', 'Bred'],
      sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
      isFeatured: true,
      inStock: true,
      stockCount: 8,
      unit: 'pair',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_42',
      name: 'Skechers Ultra Flex 3.0 Slip-Ons',
      brand: 'Skechers',
      category: 'Footwear',
      price: 5990.0,
      originalPrice: 7500.0,
      rating: 4.3,
      reviewCount: 220,
      imageUrl: 'https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=800&q=80',
      description: 'Machine washable, slip-on design with Air Cooled memory foam insole and ultra-flexible bungee lace. Perfect for casual everyday wear.',
      colors: ['Navy / White', 'Gray / Black', 'All Black'],
      sizes: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10'],
      isFeatured: false,
      inStock: true,
      stockCount: 42,
      unit: 'pair',
      isDeleted: false,
    ),

    // ── FASHION (10 products) ────────────────────────────────────────────
    ProductModel(
      id: 'prod_7',
      name: 'Urban Tech Water-Resistant Backpack',
      brand: 'Bellroy',
      category: 'Fashion',
      price: 11900.0,
      originalPrice: 14000.0,
      rating: 4.8,
      reviewCount: 88,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
      description: 'Designed for daily commute and urban travel. Padded 16" laptop pocket, hidden quick-access pocket, and water-resistant recycled fabric.',
      colors: ['Charcoal', 'Olive', 'Navy'],
      sizes: ['20L'],
      isFeatured: false,
      inStock: true,
      stockCount: 18,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_10',
      name: 'Premium Cotton Oversized Hoodie',
      brand: 'Essential Studio',
      category: 'Fashion',
      price: 5990.0,
      originalPrice: 7990.0,
      rating: 4.4,
      reviewCount: 76,
      imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80',
      description: '450 GSM heavyweight French Terry cotton. Double-lined hood, dropped shoulders, and ribbed cuffs for elevated casual streetwear aesthetic.',
      colors: ['Heather Gray', 'Pitch Black', 'Sand Khaki'],
      sizes: ['S', 'M', 'L', 'XL'],
      isFeatured: false,
      inStock: true,
      stockCount: 20,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_43',
      name: 'Slim Fit Oxford Button-Down Shirt',
      brand: 'Brooks Brothers',
      category: 'Fashion',
      price: 4990.0,
      originalPrice: 6500.0,
      rating: 4.5,
      reviewCount: 103,
      imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
      description: '100% cotton Oxford weave with a slim, tailored fit. Button-down collar and a box pleat at the back for ease of movement.',
      colors: ['White', 'Light Blue', 'Pink Stripe'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      isFeatured: false,
      inStock: true,
      stockCount: 30,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_44',
      name: 'Levi\'s 511 Slim Fit Jeans',
      brand: 'Levi\'s',
      category: 'Fashion',
      price: 6990.0,
      originalPrice: 8500.0,
      rating: 4.6,
      reviewCount: 480,
      imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
      description: 'Versatile slim-through-the-thigh denim. Sits below the waist, slim through the hip and thigh with a slim leg opening. 99% cotton.',
      colors: ['Dark Indigo', 'Medium Indigo', 'Light Stone'],
      sizes: ['28x30', '30x30', '32x30', '32x32', '34x32'],
      isFeatured: false,
      inStock: true,
      stockCount: 25,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_45',
      name: 'Ray-Ban Wayfarer Classic Sunglasses',
      brand: 'Ray-Ban',
      category: 'Fashion',
      price: 16500.0,
      originalPrice: 19900.0,
      rating: 4.7,
      reviewCount: 350,
      imageUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7574b0d?w=800&q=80',
      description: 'Iconic trapezoidal frame shape since 1952. CR-39 lenses with 100% UV protection, injected nylon frame, and metal rivets.',
      colors: ['Black / G-15 Green', 'Tortoise / Brown', 'Rubberized Black'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 22,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_46',
      name: 'Uniqlo Ultra Light Down Jacket',
      brand: 'Uniqlo',
      category: 'Fashion',
      price: 7990.0,
      originalPrice: 9990.0,
      rating: 4.6,
      reviewCount: 224,
      imageUrl: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5e?w=800&q=80',
      description: 'Packable down jacket with 640-fill power premium down. Folds into its own inner pocket for compact storage. 90% down, 10% feather.',
      colors: ['Black', 'Navy', 'Olive', 'Red'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      isFeatured: false,
      inStock: true,
      stockCount: 28,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_47',
      name: 'Tommy Hilfiger Classic Polo Shirt',
      brand: 'Tommy Hilfiger',
      category: 'Fashion',
      price: 5490.0,
      originalPrice: 6990.0,
      rating: 4.5,
      reviewCount: 165,
      imageUrl: 'https://images.unsplash.com/photo-1625910513774-5d3a0b27e0b2?w=800&q=80',
      description: 'Classic fit piqué cotton polo with embroidered Tommy Hilfiger flag logo. Three-button placket and ribbed collar and cuffs.',
      colors: ['White', 'Navy', 'Red', 'Green'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      isFeatured: false,
      inStock: true,
      stockCount: 32,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_48',
      name: 'Gucci Ophidia GG Canvas Tote',
      brand: 'Gucci',
      category: 'Fashion',
      price: 89900.0,
      originalPrice: 99000.0,
      rating: 4.8,
      reviewCount: 56,
      imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
      description: 'Signature GG canvas with double G hardware and vintage Web stripe. Spacious interior with suede lining and two internal pockets.',
      colors: ['Beige / Ebony', 'Brown / Beige'],
      sizes: ['Medium', 'Large'],
      isFeatured: true,
      inStock: true,
      stockCount: 4,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_49',
      name: 'H&M Ribbed Turtleneck Sweater',
      brand: 'H&M',
      category: 'Fashion',
      price: 2990.0,
      originalPrice: 3990.0,
      rating: 4.3,
      reviewCount: 192,
      imageUrl: 'https://images.unsplash.com/photo-1520367745676-56196b59e105?w=800&q=80',
      description: 'Fine-knit ribbed turtleneck in a slim fit. Soft and comfortable acrylic blend, perfect for layering or wearing alone in cooler months.',
      colors: ['Cream', 'Black', 'Dusty Rose', 'Sage Green'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      isFeatured: false,
      inStock: true,
      stockCount: 45,
      unit: 'pcs',
      isDeleted: false,
    ),
    ProductModel(
      id: 'prod_50',
      name: 'Fossil Leather Bifold Wallet',
      brand: 'Fossil',
      category: 'Fashion',
      price: 3990.0,
      originalPrice: 5500.0,
      rating: 4.5,
      reviewCount: 298,
      imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
      description: 'Full-grain leather bifold with 8 card slots, ID window, and 2 bill compartments. RFID-blocking technology and slim profile.',
      colors: ['Dark Brown', 'Black', 'Tan'],
      sizes: ['Standard'],
      isFeatured: false,
      inStock: true,
      stockCount: 40,
      unit: 'pcs',
      isDeleted: false,
    ),
  ];
}

